# Generated by Django 5.2.1 on 2025-06-17 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digital_twin_app",
            "0002_document_documentchunk_documentembedding_twinversion_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidatedSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(
                        help_text="Main instructions/prompt for the agent"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="OpenAI model to use (e.g., gpt-4o-mini, gpt-4-turbo)",
                        max_length=50,
                    ),
                ),
                (
                    "max_turns",
                    models.IntegerField(
                        default=20, help_text="Maximum conversation turns"
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(default=30, help_text="Timeout in seconds"),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7, help_text="Model temperature (0.0-2.0)"
                    ),
                ),
                (
                    "top_p",
                    models.FloatField(
                        default=1.0, help_text="Top-p sampling parameter"
                    ),
                ),
                (
                    "frequency_penalty",
                    models.FloatField(default=0.0, help_text="Frequency penalty"),
                ),
                (
                    "presence_penalty",
                    models.FloatField(default=0.0, help_text="Presence penalty"),
                ),
                (
                    "system_context",
                    models.TextField(
                        blank=True, help_text="Additional system context and background"
                    ),
                ),
                (
                    "tools_enabled",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of enabled tools for this agent",
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True, default=list, help_text="List of agent capabilities"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("messages_count", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "agent_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_twin_app.agentconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="AgentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("instructions_template", models.TextField()),
                ("system_context_template", models.TextField(blank=True)),
                ("default_tools", models.JSONField(default=list)),
                ("default_capabilities", models.JSONField(default=list)),
                (
                    "recommended_model",
                    models.CharField(default="gpt-4o-mini", max_length=50),
                ),
                ("recommended_temperature", models.FloatField(default=0.7)),
                ("is_system_template", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("google_access_token", models.TextField(blank=True)),
                ("google_refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("auto_reply_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("sender", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("responded", "Responded"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("ai_response", models.TextField(blank=True)),
                ("response_sent", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="digital_twin_app.emailaccount",
                    ),
                ),
                (
                    "chat_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="digital_twin_app.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "status"],
                        name="digital_twi_sender_c5fbf9_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="digital_twi_receive_e71f2d_idx"
                    ),
                ],
            },
        ),
    ]
