# Generated by Django 5.2.1 on 2025-06-29 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digital_twin_app",
            "0002_document_documentchunk_documentembedding_twinversion_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_sample", models.TextField(blank=True, null=True)),
                ("total_rows", models.IntegerField(default=0)),
                ("statistical_summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ValidatedSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("docx", "Word Document"),
                    ("txt", "Text File"),
                    ("md", "Markdown"),
                    ("csv", "CSV File"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(
                        help_text="Main instructions/prompt for the agent"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="gpt-4o-mini",
                        help_text="OpenAI model to use (e.g., gpt-4o-mini, gpt-4-turbo)",
                        max_length=50,
                    ),
                ),
                (
                    "max_turns",
                    models.IntegerField(
                        default=20, help_text="Maximum conversation turns"
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(default=30, help_text="Timeout in seconds"),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7, help_text="Model temperature (0.0-2.0)"
                    ),
                ),
                (
                    "top_p",
                    models.FloatField(
                        default=1.0, help_text="Top-p sampling parameter"
                    ),
                ),
                (
                    "frequency_penalty",
                    models.FloatField(default=0.0, help_text="Frequency penalty"),
                ),
                (
                    "presence_penalty",
                    models.FloatField(default=0.0, help_text="Presence penalty"),
                ),
                (
                    "system_context",
                    models.TextField(
                        blank=True, help_text="Additional system context and background"
                    ),
                ),
                (
                    "tools_enabled",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of enabled tools for this agent",
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True, default=list, help_text="List of agent capabilities"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("messages_count", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "agent_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_twin_app.agentconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="AgentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("instructions_template", models.TextField()),
                ("system_context_template", models.TextField(blank=True)),
                ("default_tools", models.JSONField(default=list)),
                ("default_capabilities", models.JSONField(default=list)),
                (
                    "recommended_model",
                    models.CharField(default="gpt-4o-mini", max_length=50),
                ),
                ("recommended_temperature", models.FloatField(default=0.7)),
                ("is_system_template", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CSVColumn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("data_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("statistics", models.TextField(blank=True, null=True)),
                ("is_time_column", models.BooleanField(default=False)),
                ("is_categorical", models.BooleanField(default=False)),
                ("is_numerical", models.BooleanField(default=False)),
                ("is_primary_key", models.BooleanField(default=False)),
                ("sample_values", models.TextField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="digital_twin_app.csvdataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CSVDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file_path", models.CharField(max_length=512)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="csv_documents/"),
                ),
                ("file_size", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("row_count", models.IntegerField(default=0)),
                ("column_count", models.IntegerField(default=0)),
                ("schema_summary", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "twin_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csv_documents",
                        to="digital_twin_app.twinversion",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="csvdataset",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset",
                to="digital_twin_app.csvdocument",
            ),
        ),
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("google_access_token", models.TextField(blank=True)),
                ("google_refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("auto_reply_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSeriesData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("sensor", "Sensor Data"),
                            ("csv", "CSV Data"),
                            ("api", "External API"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_text", models.CharField(blank=True, max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("total_points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "csv_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_series",
                        to="digital_twin_app.csvdocument",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_series",
                        to="digital_twin_app.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Series",
                "verbose_name_plural": "Time Series Data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("sender", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("responded", "Responded"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("ai_response", models.TextField(blank=True)),
                ("response_sent", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="digital_twin_app.emailaccount",
                    ),
                ),
                (
                    "chat_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="digital_twin_app.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "status"],
                        name="digital_twi_sender_c5fbf9_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="digital_twi_receive_e71f2d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeSeriesPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("value", models.FloatField()),
                ("notes", models.TextField(blank=True)),
                (
                    "time_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="digital_twin_app.timeseriesdata",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["time_series", "timestamp"],
                        name="digital_twi_time_se_379dbb_idx",
                    )
                ],
            },
        ),
    ]
