# Generated by Django 5.2.1 on 2025-06-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digital_twin_app",
            "0003_csvdataset_validatedsender_alter_document_file_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentembedding",
            name="embedding_type",
            field=models.CharField(default="document", max_length=50),
        ),
    ]
