# Generated by Django 5.2.1 on 2025-07-01 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin_app", "0004_documentembedding_embedding_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_tokens_used", models.BigIntegerField(default=0)),
                ("total_input_tokens", models.BigIntegerField(default=0)),
                ("total_output_tokens", models.BigIntegerField(default=0)),
                ("total_chat_sessions", models.IntegerField(default=0)),
                ("total_messages_sent", models.IntegerField(default=0)),
                ("total_documents_uploaded", models.IntegerField(default=0)),
                ("total_emails_processed", models.IntegerField(default=0)),
                ("daily_token_limit", models.IntegerField(default=1000000)),
                ("monthly_token_limit", models.BigIntegerField(default=30000000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
