# Generated by Django 5.2.1 on 2025-07-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin_app", "0008_assign_resources_to_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="agentconfiguration",
            old_name="created_by",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="user",
            new_name="uploaded_by",
        ),
        migrations.RenameIndex(
            model_name="agentusage",
            new_name="digital_twi_user_id_3631fd_idx",
            old_name="agent_usage_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="documentusage",
            new_name="digital_twi_user_id_96a2dd_idx",
            old_name="doc_usage_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenusage",
            new_name="digital_twi_user_id_33537f_idx",
            old_name="token_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="tokenusage",
            new_name="digital_twi_resourc_b1119a_idx",
            old_name="token_res_type_id_idx",
        ),
        migrations.AlterUniqueTogether(
            name="twinversion",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_shared",
        ),
        migrations.AlterField(
            model_name="twinversion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="twin_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="twinversion",
            unique_together={("user", "name", "version")},
        ),
        migrations.AddIndex(
            model_name="twinversion",
            index=models.Index(
                fields=["user", "is_active"], name="digital_twi_user_id_0ba375_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="twinversion",
            index=models.Index(
                fields=["is_shared"], name="digital_twi_is_shar_15fbc8_idx"
            ),
        ),
    ]
