# Generated by Django 5.2.1 on 2025-07-06 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_twin_app", "0009_rename_created_by_agentconfiguration_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGmailConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(help_text="OAuth2 access token for Gmail API"),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="OAuth2 refresh token for token renewal",
                        null=True,
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the access token expires", null=True
                    ),
                ),
                (
                    "scopes_granted",
                    models.JSONField(
                        default=list, help_text="List of OAuth scopes granted by user"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Gmail email address for this connection",
                        max_length=254,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the Gmail connection is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_gmail_connections",
            },
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["session", "message_index"]},
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-last_message_at", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="edit_history",
            field=models.JSONField(
                blank=True, default=list, help_text="History of edits"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="finish_reason",
            field=models.CharField(
                blank=True, help_text="Why the model stopped", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="message_index",
            field=models.IntegerField(
                default=0, help_text="Order of message in the session"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="model_used",
            field=models.CharField(
                blank=True, help_text="AI model used for this response", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="output_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                help_text="For branching conversations",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="digital_twin_app.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="temperature",
            field=models.FloatField(
                blank=True, help_text="Temperature used for this response", null=True
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="tool_outputs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Outputs from tools used"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="total_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="agent_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="digital_twin_app.agentconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="context_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated summary of the conversation"
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="Archived sessions are hidden by default"
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_pinned",
            field=models.BooleanField(
                default=False, help_text="Pinned sessions appear at top"
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="last_message_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="message_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text="User-defined tags for organization"
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated title for the session",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="total_input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="total_output_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="total_tokens_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="tools_used",
            field=models.JSONField(
                blank=True, default=list, help_text="List of tools used in this message"
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "message_index"],
                name="digital_twi_session_a12064_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "role", "-timestamp"],
                name="digital_twi_session_b6ee0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["timestamp"], name="digital_twi_timesta_02676d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "is_active", "-last_message_at"],
                name="digital_twi_user_id_825aba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "is_pinned", "-updated_at"],
                name="digital_twi_user_id_c433d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "is_archived"], name="digital_twi_user_id_efc041_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["session_id"], name="digital_twi_session_9d9722_idx"
            ),
        ),
        migrations.AddField(
            model_name="usergmailconnection",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gmail_connection",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usergmailconnection",
            index=models.Index(
                fields=["user", "is_active"], name="user_gmail__user_id_dfe494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergmailconnection",
            index=models.Index(
                fields=["email_address"], name="user_gmail__email_a_aa4bef_idx"
            ),
        ),
    ]
