# Generated by Django 5.2.1 on 2025-07-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "digital_twin_app",
            "0010_usergmailconnection_alter_chatmessage_options_and_more",
        ),
    ]

    operations = [
        # Rename columns to match the model definition
        migrations.RunSQL(
            "ALTER TABLE user_gmail_connections RENAME COLUMN connected_at TO created_at;",
            reverse_sql="ALTER TABLE user_gmail_connections RENAME COLUMN created_at TO connected_at;"
        ),
        migrations.RunSQL(
            "ALTER TABLE user_gmail_connections RENAME COLUMN last_sync TO updated_at;",
            reverse_sql="ALTER TABLE user_gmail_connections RENAME COLUMN updated_at TO last_sync;"
        ),
    ]
